### ISSUE TITLE
Tea and coffee commands backwards (multiple dokis)

### ISSUE THREAD

**Issue by sayori3** [sayori3/dokis#34]
see title

**Comment by tangalbert919** [comment]
*dabs* Fixed.

**Comment by tangalbert919** [comment]
Note: Other dokis may be affected by this bug as well.

**Comment by sayori3** [comment]
when you fix problems at the speed of sound

**Comment by tangalbert919** [comment]
First, fuck you Cheezy.

Second, Natsuki and Sayori have their fucksie-wucksies, and Monika needs a typo fix.

**Comment by tangalbert919** [comment]
Now this is fixed.
